name: local_storage_service
description: Dart package which manages local storage services
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter_secure_storage: ^4.2.1
  shared_preferences: ^2.0.6